[project]
name = "immich-bulk-add-faces-to-images"
version = "0.2.1"
description = "Script for bulk assigning faces to assets within a specified album in Immich"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
