[project]
name = "immich-bulk-add-faces-to-images"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "requests>=2.32.3",
]
